<script lang="ts">
  import { unitOfMeasureStore } from '$lib/stores/unitOfMeasureStore'; // Assuming this store handles DBOs
  import type { UnitOfMeasureDbo } from '$lib/services/dbService'; // Import DBO type
  import { createEventDispatcher, onMount } from 'svelte';

  export let unitToEdit: UnitOfMeasureDbo | null = null;

  // Form fields based on UnitOfMeasureDbo
  let localId: number | undefined = undefined; // Dexie's auto-incremented ID
  let id: string | null = null; // Server's ID (string or null if not synced)
  let codigo: string = '';    // Business key
  let Nombre: string = '';
  let Abreviatura: string | null = null; // Optional
  let Orden: number = 0; // Default to 0 or 1 as per preference
  let Estado: boolean = true; // Default to true for new units

  let isEditing = false;

  const dispatch = createEventDispatcher();

  const initializeForm = (unit: UnitOfMeasureDbo | null) => {
    if (unit) {
      localId = unit.localId;
      id = unit.id; // Server ID
      codigo = unit.codigo;
      Nombre = unit.Nombre;
      Abreviatura = unit.Abreviatura;
      Orden = unit.Orden;
      Estado = unit.Estado;
      isEditing = true;
    } else {
      localId = undefined;
      id = null;
      codigo = '';
      Nombre = '';
      Abreviatura = null;
      Orden = 0; // Default for new
      Estado = true; // Default for new
      isEditing = false;
    }
  };

  onMount(() => {
    initializeForm(unitToEdit);
  });

  // Watch for changes in unitToEdit prop
  $: initializeForm(unitToEdit);
  
  const handleSubmit = async () => {
    if (!Nombre || !codigo) {
      alert('Codigo and Nombre are required.');
      return;
    }

    const unitData: Omit<UnitOfMeasureDbo, 'localId' | 'sincronizado' | 'fechaModificacion' | 'id' | 'offlineId'> & 
                    Partial<Pick<UnitOfMeasureDbo, 'id' | 'offlineId'>> = {
      codigo: codigo,
      Nombre: Nombre,
      Abreviatura: Abreviatura || null,
      Orden: Number(Orden), // Ensure Orden is a number
      Estado: Estado,
    };

    if (isEditing && localId) {
      // For update, we need to pass the localId and the fields to be updated.
      // The store should handle creating the correct payload for syncService.
      const updatePayload: Partial<UnitOfMeasureDbo> = {
        ...unitData,
        fechaModificacion: new Date(),
        sincronizado: false, // Mark as unsynced on modification
      };
      await unitOfMeasureStore.update(localId, updatePayload, codigo); // Pass 'codigo' as entityKey for sync
    } else {
      // For add, create a full DBO object.
      // localId is auto-generated by Dexie.
      // id (server Id) is null initially.
      const newUnitDbo: Omit<UnitOfMeasureDbo, 'localId'> = {
        ...unitData,
        id: null, // Server ID is null for new records
        sincronizado: false,
        fechaModificacion: new Date(),
        offlineId: `offline_${Date.now()}` // Example temporary offline ID
      };
      await unitOfMeasureStore.add(newUnitDbo as UnitOfMeasureDbo); // Cast needed if store expects full DBO
    }
    
    dispatch('formSubmitted'); // Notify parent component
    // resetForm(); // Do not call resetForm here, let parent handle it via prop change or explicit call
  };

  // This resetForm is now typically called by parent by setting unitToEdit to null
  // or by a dedicated "clear" button if one exists.
  // If called explicitly (e.g. cancel button), it should re-initialize.
  const handleCancel = () => {
    initializeForm(null); // Resets to new unit state
    unitToEdit = null; // Clear the prop effect as well
    dispatch('formCleared');
  };

</script>

<form on:submit|preventDefault={handleSubmit} class="p-4 border rounded shadow-md mb-4 bg-white">
  <h3 class="text-lg font-semibold mb-3 text-gray-800">{isEditing ? 'Edit' : 'Add'} Unit of Measure</h3>
  
  <div class="mb-3">
    <label for="codigo" class="block text-sm font-medium text-gray-700">Codigo (e.g., kg, lt):</label>
    <input type="text" id="codigo" bind:value={codigo} required class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" readonly={isEditing} />
    {#if isEditing}
      <p class="text-xs text-gray-500 mt-1">Codigo cannot be changed for existing units.</p>
    {/if}
  </div>

  <div class="mb-3">
    <label for="nombre" class="block text-sm font-medium text-gray-700">Nombre:</label>
    <input type="text" id="nombre" bind:value={Nombre} required class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" />
  </div>

  <div class="mb-3">
    <label for="abreviatura" class="block text-sm font-medium text-gray-700">Abreviatura (Optional):</label>
    <input type="text" id="abreviatura" bind:value={Abreviatura} class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" />
  </div>

  <div class="mb-3">
    <label for="orden" class="block text-sm font-medium text-gray-700">Orden:</label>
    <input type="number" id="orden" bind:value={Orden} required class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" />
  </div>

  <div class="mb-4">
    <label for="estado" class="flex items-center text-sm font-medium text-gray-700">
      <input type="checkbox" id="estado" bind:checked={Estado} class="mr-2 h-4 w-4 text-indigo-600 border-gray-300 rounded focus:ring-indigo-500" />
      Estado (Active)
    </label>
  </div>

  <div class="flex items-center space-x-2">
    <button type="submit" class="bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:opacity-50" disabled={!codigo || !Nombre}>
      {isEditing ? 'Update Unit' : 'Add Unit'}
    </button>
    {#if isEditing}
      <button type="button" on:click={handleCancel} class="bg-gray-200 hover:bg-gray-300 text-gray-700 font-semibold py-2 px-4 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-400">
        Cancel Edit
      </button>
    {/if}
  </div>
</form>
